name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies and Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --workers=4 --reporter=line,allure-playwright

      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Move Allure results to the right directory
        run: |
          mkdir -p build/allure-results
          mv allure-results/* build/allure-results || echo "No files to move in allure-results"

      - name: Check Allure results
        run: ls -R build/allure-results

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Build and publish Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results